### ISSUE TITLE
Installing Shoes 4 from github failed

### ISSUE THREAD

**Issue by xinqinglxl** [shoes/shoes4#1226] opened 2016-03-08 03:42 UTC
I'am try to install shoes4 from source and occurred an error .
First I download the source from github.
Then >cd  D:\tools\ruby\shoes\shoes4_src\shoes4-master
And run >rake install:all it output the following error

```
D:\tools\ruby\shoes\shoes4_src\shoes4-master>rake install:all
cd ./shoes-core && rake install
fatal: Not a git repository (or any of the parent directories): .git
shoes-core 4.0.0.pre5 built to pkg/shoes-core-4.0.0.pre5.gem.
rake aborted!
Couldn't install gem, run `gem install D:/tools/ruby/shoes/shoes4_src/shoes4-mas
ter/shoes-core/pkg/shoes-core-4.0.0.pre5.gem' for more detailed output
D:\jruby-9.0.5.0\bin\rake:23:in `<top>'
Tasks: TOP => install
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [cd ./shoes-core && rake install...]
D:/tools/ruby/shoes/shoes4_src/shoes4-master/tasks/gem.rb:22:in `block in (root)
'
D:\jruby-9.0.5.0\bin\rake:23:in `<top>'
Tasks: TOP => install:all => install:shoes-core
(See full trace by running task with --trace)
```

After that I try >jruby -S gem install D:\tools\ruby\shoes\shoes4_src\shoes4-master\shoes-core\pkg\shoes-core-4.0.0.pre5.gem

```
Building native extensions.  This could take a while...
ERROR:  Error installing D:\tools\ruby\shoes\shoes4_src\shoes4-master\shoes-core
\pkg\shoes-core-4.0.0.pre5.gem:
        ERROR: Failed to build gem native extension.

    D:/jruby-9.0.5.0/bin/jruby.exe -rubygems D:/jruby-9.0.5.0/lib/ruby/gems/shar
ed/gems/rake-10.5.0/bin/rake RUBYARCHDIR=D:/jruby-9.0.5.0/lib/ruby/gems/shared/e
xtensions/universal-java-1.7/2.2.0/shoes-core-4.0.0.pre5 RUBYLIBDIR=D:/jruby-9.0
.5.0/lib/ruby/gems/shared/extensions/universal-java-1.7/2.2.0/shoes-core-4.0.0.p
re5
rake aborted!
Errno::ENOENT: No such file or directory - D:/jruby-9.0.5.0/lib/ruby/gems/shared
/gems/shoes-core-4.0.0.pre5/ext/install/shoes.bat

Tasks: TOP => default => install_script
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in D:/jruby-9.0.5.0/lib/ruby/gems/shared/gems/sh
oes-core-4.0.0.pre5 for inspection.
Results logged to D:/jruby-9.0.5.0/lib/ruby/gems/shared/extensions/universal-jav
a-1.7/2.2.0/shoes-core-4.0.0.pre5/gem_make.out
```

Here is my env
OS: Windows 7
jruby: jruby 9.0.5.0
shoes: have already installed 4.0.0.pre5 (does this takes any effect？)

**Comment by PragTob** [comment] 2016-03-08 11:35
Hi there, thank you for your bug report!

Could you please run `rake install:all --trace` to give us the full output?

Or run `cd ./shoes-core && rake install --trace` - maybe our cd syntax doesn't work on Windows and the rake task is broken on Windows (we don't have a regular dev on Windows these days so some Windows bugs around tooling are likely to go unnoticed - sorry about that!)

Cheers,
Tobi

**Comment by xinqinglxl** [comment] 2016-03-09 01:11
Thank you for the reply.
> Could you please run rake install:all --trace to give us the full output?
Here is the output with '--trace' option
```
D:\tools\ruby\shoes\shoes4_src\shoes4-master>rake install:all --trace
** Invoke install:all (first_time)
** Invoke install:shoes-core (first_time)
** Execute install:shoes-core
cd ./shoes-core && rake install
fatal: Not a git repository (or any of the parent directories): .git
shoes-core 4.0.0.pre5 built to pkg/shoes-core-4.0.0.pre5.gem.
rake aborted!
Couldn't install gem, run `gem install D:/tools/ruby/shoes/shoes4_src/shoes4-mas
ter/shoes-core/pkg/shoes-core-4.0.0.pre5.gem' for more detailed output
D:\jruby-9.0.5.0\bin\rake:23:in `<top>'
Tasks: TOP => install
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [cd ./shoes-core && rake install...]
D:/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/file_utils.rb:67
:in `block in create_shell_runner'
org/jruby/RubyProc.java:318:in `call'
D:/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/file_utils.rb:57
:in `sh'
D:/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/file_utils_ext.r
b:34:in `sh'
D:/tools/ruby/shoes/shoes4_src/shoes4-master/tasks/gem.rb:22:in `block in (root)
'
org/jruby/RubyProc.java:318:in `call'
D:/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/task.rb:240:in `
block in execute'
org/jruby/RubyArray.java:1560:in `each'
D:/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/task.rb:235:in `
execute'
D:/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/task.rb:179:in `
block in invoke_with_call_chain'
D:/jruby-9.0.5.0/lib/ruby/stdlib/monitor.rb:211:in `mon_synchronize'
D:/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/task.rb:172:in `
invoke_with_call_chain'
D:/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/task.rb:201:in `
block in invoke_prerequisites'
org/jruby/RubyArray.java:1560:in `each'
D:/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/task.rb:199:in `
invoke_prerequisites'
D:/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/task.rb:178:in `
block in invoke_with_call_chain'
D:/jruby-9.0.5.0/lib/ruby/stdlib/monitor.rb:211:in `mon_synchronize'
D:/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/task.rb:172:in `
invoke_with_call_chain'
D:/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/task.rb:165:in `
invoke'
D:/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/application.rb:1
50:in `invoke_task'
D:/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/application.rb:1
06:in `block in top_level'
org/jruby/RubyArray.java:1560:in `each'
D:/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/application.rb:1
06:in `block in top_level'
D:/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/application.rb:1
15:in `run_with_threads'
D:/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/application.rb:1
00:in `top_level'
D:/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/application.rb:7
8:in `block in run'
D:/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/application.rb:1
76:in `standard_exception_handling'
D:/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/application.rb:7
5:in `run'
D:/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rake-10.5.0/bin/rake:33:in `<top>'
org/jruby/RubyKernel.java:955:in `load'
D:\jruby-9.0.5.0\bin\rake:23:in `<top>'
Tasks: TOP => install:all => install:shoes-core
```

And, here is the tree of jruby-9.0.5.0\lib\ruby\gems\shared\gems\shoes-core-4.0.0.pre5 dir after install failed.
```
D:.
├─bin
│      shoes-picker
│      shoes-stub
│
└─ext
    └─install
            Rakefile
```

**Comment by jasonrclark** [comment] 2016-12-15 05:13
Hi @xinqinglxl! Sorry for the long delay, but I'm back to working on Shoes and tonight I duplicated your issue. 🎉 

So the issue isn't with the install, it's actually the gem build which is mixed up. The directory you show there is actually all that's made it into your built gem! Why?, Well, your shell doesn't have the `git` command available. (Note for working around, if you run this from a shell with `git`, you'll have better success. I did that first with a Powershell instance that had git before moving over to cmd.exe which lacked it)

As is fairly common practice in Ruby gems, [we use `git ls-files` to obtain the list of files to include in the gem on build](https://github.com/shoes/shoes4/blob/dd7114f998ffcefa77a635f00790e627fa58d171/shoes-core/shoes-core.gemspec#L15). The effect of this, though, is to end up with an empty list of the backticked call to `git` fails, which quietly goofs things up.

I've done a bit of looking around to see if others have more clever ideas on this. Here's the options (with one "clever" idea of my own):

1) Use the `git ls-files` trick (Bundler and Sidekiq)
2) Include `lib/**/*` and a few other specific files (Rails gems). We need more than just that directory, but it's a finite number we could include.
3) Go an entirely different route using `Manifest.txt` and the hoe gem (Rubygems)
4) Check the gemspec files list after the git command and explicitly error out if it's empty with a message about likely causes (my 🔅 idea)

I'd probably choose either 2) or 4) and given that we want to be a Windows friendly project it does seem worth addressing. What do you think @PragTob? Any of those options grab you in particular?

**Comment by wasnotrice** [comment] 2016-12-15 16:26
@jasonrclark I have always thought the rationale behind `Manifest.txt` is sound: the gem should specify exactly what files are included in the build. I'd vote for 2), since it gives us (some of) that same benefit, but without introducing another dependency. The git trick is fine, but it inevitably includes more files than you actually want. Plus, we shouldn't require git to be able to install Shoes.

**Comment by PragTob** [comment] 2016-12-17 11:24
Ah sorry I missed this, with @wasnotrice on this I think that sounds good and I think that's also what you started implementing :)

**Comment by jasonrclark** [comment] 2016-12-19 04:55
Changes on this to properly list files without `git` are merged to master. @xinqinglxl you should be able to install from source now on Windows. Thanks again for the report! ✨

**Closed** 2016-12-19 04:54 UTC
Labels: bug, install, windows
