### ISSUE TITLE
Right hand side grey bar

### ISSUE THREAD

**Issue by miller0929** [shoes/shoes4#817] opened 2014-07-30 06:53 UTC
I just noticed that there will be a grey bar appearing on the right hand side of the app window if one has the app background turned to white. Initially no grey bar will show when app windows is launched. However, one simple click on a button, this nasty grey bar will come and stay forever... Please fix it!

Simple code like this will demo. Run the code on a Mac OS 10.9.2 with Shoes 4: shoes xxx.rb. The code is:
Shoes.app do
    background white
    flow margin: 12 do
        button "Stop" do
        end
    end
end

**Comment by PragTob** [comment] 2015-01-14 18:29
I can't reproduce (Linux here) :( @miller0929 could you please retry from current master? When running from master please make sure to do `bin/shoes your_file.rb` otherwise it will use the installed gem executable from an older version.

Thank you!

**Comment by PragTob** [comment] 2015-04-12 19:19
Closing for now as feedback is needed (can't reproduce)

**Closed by PragTob** 2015-04-12 19:19 UTC
Labels: bug, need feedback
