### ISSUE TITLE
Key handler triggers when holding key - updating lags behind

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#751] opened 2014-06-09 09:43 UTC
Try run `samplaes/simple-keypress.rb` and then hold a key:

**expected behavior:** it should make a stream of output that the key is pressed

**actual behavior:** the UI only shows all the paras notifying the key press when you release the button - you can see the symbols update in real time in the console though.

Probably a problem with redrawing not being triggered.

**Comment by jasonrclark** [comment] 2015-05-26 05:18
Is this still happening for you @PragTob? When I tried it locally, I ended up with it showing the stream of para's without releasing the button. Seems like it's either fixed, or it's platform specific.

**Comment by KCErb** [comment] 2015-08-26 21:46
Works for me as well . . . though I'm on OS X like @jasonrclark

**Comment by PragTob** [comment] 2015-08-28 15:33
Still happens for me, marking it a Linux thing :(

**Comment by jasonrclark** [comment] 2015-10-18 21:24
When I marked this for pre5, I think I expected to be able to dup it on Mac. Since it's linux only, you mind me popping it back in the rc1 bin @PragTob? Feeling like getting a pre5 release buttoned up in the near future since it's been a while and we have a small set of things it'd be nice to get in the wild.

**Comment by jasonrclark** [comment] 2017-08-21 04:02
Confirmed this still happens on Ubuntu. Will see whether there's any sort of async update we can trigger after our key-handling blocks have run, since the native behavior doesn't kick anything until we've released the keypress fully.

**Comment by jasonrclark** [comment] 2017-09-21 05:06
Based on reading I did around https://github.com/shoes/shoes4/issues/1440, I'm concluding that we can't do much about this.

I tested adding in several additional redrawing hooks, and even the most aggressive of them (putting in forced `redraw`s and `update` instead of just `layout`) didn't have any effect. It seems as though the OS-specific behavior is just blocking any screen painting for me until I've released the key, which is a bummer but not at a level we can work around.

Based on this, I'm going to close this out unless someone has additional insight to contribute (and reopen with).

**Closed by jasonrclark** 2017-09-21 05:06 UTC
Labels: bug, linux
