### ISSUE TITLE
Can't run a second app after main app stops

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1298] opened 2016-11-23 19:55 UTC
Don't know whether we want to support this or not, but if you run this code, it crashes after you close the first app:

```
Shoes.app do
  para "first"
end

Shoes.app do
  para "second"
end
```

In Shoes 3 it behaves in a further different way--it will just start each app immediately, without blocking on the first app running.

**Comment by PragTob** [comment] 2016-11-23 20:55
Hmmm... I'd tend to not support that. Seems like no major use case to me. Also the rework from where we start the SWT drawing loop might not be too easy...

That said, theoretically it'd be nice to be able to have two separate apps at a time to see that we don't rely on global state.

**Comment by ccoupe** [comment] 2016-11-24 06:37
FWIW,  I have seen user  scripts that have had two Shoes.app {} invocations - they complained  about Shoes 3 drawing each window in the same place so only the second one shows visually and no way to communicated between then - a very different issue.  I directed them to use Shoes.Window and only have one Shoe.app call because it's more than weird when you get inside app method and variables (which is a global state - think full screen)

**Comment by jayjlawrence** [comment] 2016-12-07 20:44
New to shoes here so take my comments lightly. In the referenced issue above I raise the same. My expected behaviour would be that app1 runs until closed and then app2 will run until close - sequentially. The described Shoes3 behaviour, although does make sense, wasn't what I would expect. As a new user I expect that the Shoes.app blocks until closed/quit and then continues processing after the Shoes.app BLOCK.

My motivation for the expected sequential behaviour is to avoid the jruby Shoes startup cost and run a simple while loop to load and run my script more quickly. All this about globals - I'd expect they'd be reinitialized for the 2nd app just the same as the 1st app.

Perhaps a pattern using one App and opening/closing windows instead is the way to go. I will explore this when I have a moment. Perhaps I'll create a sample :)

**Closed** 2016-12-15 11:17 UTC
Labels: bug, compatibility, need feedback
